# Generated by Django 3.2.20 on 2023-07-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bid_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='author',
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.auction_item'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
