# Generated by Django 3.2.20 on 2023-07-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230718_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='new_price',
        ),
        migrations.AlterField(
            model_name='auction_item',
            name='price',
            field=models.FloatField(default=models.FloatField()),
        ),
    ]
