# Generated by Django 3.2.20 on 2023-07-18 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230718_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_item',
            old_name='datetime',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='auction_item',
            name='active',
        ),
        migrations.AddField(
            model_name='auction_item',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='auction_item',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('closed', 'closed')], default='active', max_length=10),
        ),
    ]
