# Generated by Django 3.2.20 on 2023-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230718_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_item',
            name='txId',
            field=models.CharField(blank=True, default=None, max_length=66, null=True),
        ),
    ]
