# Generated by Django 3.2.20 on 2023-07-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auction_item_txid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_item',
            name='winner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
